- name: demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}" #item is a reserved word
    loop:
    - Ramesh
    - Suresh
    - Naresh